# Generated by Django 4.2.6 on 2025-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
