# Generated by Django 4.2.6 on 2025-03-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
