# Generated by Django 4.2.6 on 2025-04-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='Item_name',
        ),
    ]
